name: workflow_tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Python 3.x
      - name: Set up Python 3.X
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Install Google Chrome and ChromeDriver
      - name: Install Google Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          
          # Fetch Chrome Version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')

          # Get only the major version number
          CHROME_VERSION_MAJOR=$(echo $CHROME_VERSION | cut -d '.' -f 1)

          # Download the matching ChromeDriver version
          wget -N https://chromedriver.storage.googleapis.com/${CHROME_VERSION_MAJOR}/chromedriver_linux64.zip || wget -N https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION_MAJOR}/chromedriver_linux64.zip

          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm chromedriver_linux64.zip google-chrome-stable_current_amd64.deb

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the tests
      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings